### ISSUE TITLE
财新网和财新周刊的Surge模块均已失效

### ISSUE THREAD

**Issue by cjyy46** [I-am-R-E/Functional-Store-Hub#1]
财新网和财新周刊的Surge模块均已失效 劳烦更新下 谢谢！

**Comment by I-am-R-E** [comment]
已修复，更新脚本即可

**Comment by cjyy46** [comment]
> 已修复，更新脚本即可

脚本已更新，但依旧无法阅读文章，请核实。

**Comment by I-am-R-E** [comment]
脚本有效的

**Comment by cjyy46** [comment]
> 脚本有效的

我是用的Surge模块 链接用下面两个
https://raw.githubusercontent.com/I-am-R-E/Functional-Store-Hub/Master/CaiXin/Surge.sgmodel

https://raw.githubusercontent.com/I-am-R-E/Functional-Store-Hub/Master/CaiXinWeekly/Surge.sgmodule

是我设置有问题么？为什么之前都好用，这次更新后却不行呢。

**Comment by cjyy46** [comment]
> 脚本有效的

我很确定其它设置没变，仅更新脚本后依旧不能使用，不知道问题出在哪里。

**Comment by I-am-R-E** [comment]
https://raw.githubusercontent.com/I-am-R-E/Functional-Store-Hub/Master/CaiXin/Surge.sgmodel

建议删除模块重新添加

这里可以获得更好的交流体验 https://t.me/Functional_Store_Hub

**Comment by cjyy46** [comment]
> https://raw.githubusercontent.com/I-am-R-E/Functional-Store-Hub/Master/CaiXin/Surge.sgmodel
> 
> 
> 
> 建议删除模块重新添加
> 
> 
> 
> 这里可以获得更好的交流体验 https://t.me/Functional_Store_Hub

tg私聊你了
