### ISSUE TITLE
建议给Surge的网易云音乐节点增加test-url参数

### ISSUE THREAD

**Issue by Infatuation-Fei** [I-am-R-E/Functional-Store-Hub#2]
建议给这个Surge的网易音解锁节点(https://github.com/I-am-R-E/Functional-Store-Hub/blob/Master/NeteaseMusic/AgentNode/Surge.list) 增加test-url参数，方便进行延时测试，效果等于圈X里面的server_check_url参数，看您的圈X的网易云节点中写了server_check_url=http://interface3.music.163.com， 建议给Surge的那个也加上test-url=http://interface3.music.163.com

**Comment by I-am-R-E** [comment]
谢谢建议 已经添加
